name: Nebula non-HW Test

on: [push, pull_request]

jobs:
  non-HW-Test:
    runs-on: self-hosted
    strategy:
        matrix:
            python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Workaround for setup python
        run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nebula
        run: |
          python -m pip install .
          python -c "import nebula"

      - name: non-HW Test
        run: |
          cd tests
          pytest test_downloader.py test_cli.py -s -v
